# MMAT Configuration for test-mmat project

# Environment Configuration
environment:
  type: browser
  parameters:
    browser_type: chromium
    headless: false # Set to false to see the browser during testing
    baseUrl: file:///c:/Projects/Mmat/test-mmat/index.html # Use the local HTML file

# Model Configuration
models:
  vision:
    type: vision_model
    parameters:
      api_url: http://172.29.32.1:1234/v1
      model_name: mistralai/mistral-small-3.2
  reasoning:
    type: reasoning_model
    parameters:
      api_url: http://172.29.32.1:1234/v1
      model_name: mistralai/magistral-small

# Test Suite Configuration (This will be populated by mmat generate)
test_suite:
  name: Sample Login Test Suite
  description: Generated test suite for sample login functionality
  test_cases: [] # Empty initially, will be filled by generate

# Reporter Configuration
reporters:
  - type: json_reporter
    parameters:
      output_file: reports/mmat_report.json
